softdevteam/diffract

.travis.yml
grammars/java.y
src/main.rs

Run rustfmt on Travis.

---

Cargo.lock
Cargo.toml
src/lib/mod.rs
src/main.rs

Simplify argument parsing.

---

src/main.rs

This is a small improvement in `main()`, but I've had to use the `unreachable!()` macro to avoid errors like this:
```rust
error[E0308]: match arms have incompatible types
--> src/main.rs:153:22
|
153 |       let extension2 = match Path::new(&args.arg_diff_file).extension() {
|  ______________________^
154 | |         Some(ext) => ext.to_str().unwrap(),
155 | |         None => {
156 | |             exit_on_err(format!("Cannot determine file type of {}.", args.arg_diff_file));
157 | |             // unreachable!()
158 | |         }
159 | |     };
| |_____^ expected &str, found ()
|
= note: expected type `&str`
found type `()`
```
Is there a better way?

Factor out repeated code in main.

---

src/lib/action.rs
src/lib/emitters.rs
src/lib/matchers.rs
src/main.rs

This PR allows the user to render JSON output. Format matches GumTree output. Default is to produce no output.
e.g. 
```sh
>>> ./target/debug/rstreediff -m Myers -o Json tests/empty.calc tests/one.calc
{
"matches": [
{
"src": 2,
"dest": 2
},
{
"src": 1,
"dest": 1
},
{
"src": 3,
"dest": 3
},
{
"src": 0,
"dest": 0
}
],
"actions": [
{
"action": "insert",
"tree": 2,
"parent": 2,
"at": 0
}
]
}
```
The output matches GumTree output and is valid JSON:
```sh
>>> ./target/debug/rstreediff -m Myers -o Json tests/Test0.java tests/Test1.java >output.json
>>> import json
>>> with open("output.json") as fp:
...     j = json.loads(fp.read())
...
>>> j['matches']
[{u'dest': 2, u'src': 2}, {u'dest': 1, u'src': 1}, {u'dest': 6, u'src': 12}, {u'dest': 9, u'src': 5}, {u'dest': 10, u'src': 6}, {u'dest': 12, …
```

Second infrastructure PR

---

src/lib/sequence.rs

This PR is needed to implement the Zhang-Shasha algorithm, it adds:
* Levenshtein distance for string-like types
* Changes LCSS algorithm to use fixed capacity vectors.
No user-facing changes. 
**Needs squashing.**

Levenshtein algorithm for string-like types

---

.travis.yml
src/lib/action.rs
src/lib/ast.rs
src/lib/emitters.rs
src/lib/matchers.rs
src/lib/sequence.rs
tests/test_ast.rs

rustfmt has changed recently, and this PR brings the repo up to date...

Formatting changes

---

src/lib/ast.rs
src/lib/emitters.rs
src/main.rs

A few simplifications I noticed for rstreediff. Note: all the tests pass, but I don't know if the tests touch all of these code paths. So it might be worth checking that.

Simplifications.

---

Cargo.toml
src/main.rs
tests/test_ast.rs
tests/test_hqueue.rs
tests/test_matcher.rs

If we can merge this, I will change the GitHub URL also...

Change name of library and binary.

---

src/lib/mod.rs

Just raising this as a separate PR because it will need to be merged into several ongong branches...

Update rust env.

---

src/lib/emitters.rs

**Needs squashing**
This PR improves the mapping and edit script visualisations that are provided in Graphviz format (for debugging), in three ways:
* Borders are drawn between the source and destination ASTs
* The two borders are lined up
*  Whitespace nodes now have their whitespace made visible (e.g. "\n" now appears in the graphs).
On master branch:
* [map_master.pdf](https://github.com/softdevteam/diffract/files/1382661/map_master.pdf)
* [edit_master.pdf](https://github.com/softdevteam/diffract/files/1382662/edit_master.pdf)
On this branch:
* [map.pdf](https://github.com/softdevteam/diffract/files/1382664/map.pdf)
* [edit.pdf](https://github.com/softdevteam/diffract/files/1382665/edit.pdf)

Improve gv output

---

src/lib/action.rs
src/lib/ast.rs
src/lib/matchers.rs
src/lib/myers_matcher.rs
src/lib/sequence.rs

**NEEDS SQUASHING**
Fixes #39
Fixes #41

ASTs keep track of their root node

---

src/lib/ast.rs

Use latest lrpar API.

---

src/lib/edit_script.rs
src/main.rs

I have added new new edit script generator which prints empty script.

Added new edit script generator.

---

src/lib/edit_script.rs
src/lib/gt_matcher.rs
src/lib/matchers.rs
src/lib/myers_matcher.rs
src/lib/patch.rs
src/main.rs
tests/test_edit_script.rs

Minor improvements suggested by Clippy. I'm never really sure whether it's sensible to keep these commits separate (for merging, clearly it's better to separate them for reviewing), but potentially they could be collapsed into a single commit.

Clippy suggestions

---

tests/test_hqueue.rs

Remove unnecessary configuration.

---

src/lib/ast.rs
src/main.rs
tests/test_edit_script.rs
tests/test_matcher.rs

This should have gone in the last PR. Mea maxima culpa.

Code improvements suggested by clippy and rustfmt.

---

src/lib/action.rs
src/lib/chawathe98_matcher.rs
src/lib/edit_script.rs
src/lib/emitters.rs
src/lib/gt_matcher.rs
src/lib/hqueue.rs
src/lib/matchers.rs
src/lib/mod.rs
src/lib/myers_matcher.rs
src/lib/patch.rs
src/lib/sequence.rs
src/main.rs
tests/test_edit_script.rs

1) Completed the induced graph builder with tests. 
-> This has several methods which have been implemented from the paper as described. 
2) Completed the pruning method. 
-> This method will remove edges that violate the rules defined. 
-> There is also lower bound and upper bound functions which are also used to remove edges.

Induced graph - Added Changes. (Third Stage -- Initial) 

---

src/lib/hqueue.rs
src/lib/matchers.rs
src/main.rs

This PR removes some code which should not have been committed, and adds some extra information for debugging.

Improve debug code

---

src/lib/action.rs

Very small API change, needed in an (ongoing) bugfix branch.

Test whether edit scripts are empty.

---

rustfmt.toml
src/lib/action.rs
src/lib/ast.rs
src/lib/chawathe98_matcher.rs
src/lib/edit_script.rs
src/lib/emitters.rs
src/lib/fingerprint.rs
src/lib/hqueue.rs
src/lib/matchers.rs
src/lib/null_matcher.rs
src/lib/parser.rs
src/lib/sequence.rs
src/main.rs
tests/test_ast.rs
tests/test_hqueue.rs

Format all code at line length 100.

---

src/lib/chawathe98_matcher.rs
src/lib/matchers.rs
src/lib/mod.rs
src/lib/myers_matcher.rs
src/lib/sequence.rs
src/lib/zs_matcher.rs
src/main.rs

Outline of a module for the Zhang-Shasha tree matching algorithm. Some small refactorings for readability / remove code duplication.

Outline zhang shasha

---

src/lib/matchers.rs
src/lib/mod.rs
src/lib/similarity.rs

Simple refactoring of code that isn't much used yet.

Factor out subtree similarity computations.

---

src/lib/chawathe98_matcher.rs

Remove unused variable from test.

---

src/lib/ast.rs
src/lib/matchers.rs

Some small API changes needed by the ZS work.

Small api changes

---

src/lib/action.rs
src/lib/ast.rs
src/lib/chawathe98_matcher.rs
src/lib/edit_script.rs
src/lib/emitters.rs
src/lib/fingerprint.rs
src/lib/hqueue.rs
src/lib/labelmaps.rs
src/lib/matchers.rs
src/lib/sequence.rs
src/lib/similarity.rs
src/lib/zs_matcher.rs
tests/common.rs

Implement Clippy suggestions.

---

src/lib/action.rs
src/lib/ast.rs
src/lib/chawathe98_matcher.rs
src/lib/edit_script.rs
src/lib/emitters.rs
src/lib/fingerprint.rs
src/lib/gt_matcher.rs
src/lib/label_maps.rs
src/lib/matchers.rs
src/lib/mod.rs
src/lib/myers_matcher.rs
src/lib/null_matcher.rs
src/lib/parser.rs
src/lib/qgram.rs
src/lib/sequence.rs
src/lib/similarity.rs
src/lib/zs_matcher.rs
src/main.rs
tests/common.rs
tests/test_ast.rs

Because I haven't been able to run rustfmt for a while, a number of files have gotten out of sync. This PR fixes that.

rustfmt over whole crate.

---

src/lib/info_tree.rs
src/lib/mod.rs
src/lib/rted.rs

This is the first of several PRs implementing the RTED algorithm of Pawlik and Augsten (2011).
This PR includes some API changes, the RTED config struct and its constructor.

RTED -- first PR

---

src/lib/info_tree.rs
src/lib/rted.rs

Add some getters and setters to the RTED module.

RTED -- second PR

---

src/lib/ast.rs
src/lib/emitters.rs
src/lib/mod.rs
src/lib/multi_mappings.rs
src/lib/parser.rs

Commits can be kept separate, explanations are in each message.

Changes suggested by Clippy
