src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/mod.rs, src/main.rs
An *action* in a tree differ, is some operation that transforms part of an AST (e.g. by deleting a node or inserting a new one).
This PR adds a new `treediff::action` module, which implements the four actions used by GumTree:
* Delete
* Insert
* Move
* Update
These can be seen in the original [Java code here](https://github.com/GumTreeDiff/gumtree/tree/develop/core/src/main/java/com/github/gumtreediff/actions/model).
It may also be useful to see the GT [code that applies actions to trees](https://github.com/GumTreeDiff/gumtree/blob/297b8f03752cd1a2dc973f637f845b79bcec5741/core/src/main/java/com/github/gumtreediff/actions/ActionUtil.java), and a [concrete implementation of a GT tree](https://github.com/GumTreeDiff/gumtree/blob/297b8f03752cd1a2dc973f637f845b79bcec5741/core/src/main/java/com/ …
=> New "Action" module

Cargo.lock, src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/matchers.rs, src/lib/mod.rs, src/main.rs
The PR contains some basic infrastructure for a `matchers` module. A matcher is an algorithm which compares two ASTs, and produces a mapping between similar nodes.
This PR contains some basic structs, constructors, etc. and an implementation of the traits needed to produce a GrahViz description of the two ASTs and their mappings. This can be output on the command line with the new `-m <file>` flag. Mappings between AST nodes are shown with dashed lines, rather than solid, for example:
```sh
$ ./target/debug/rstreediff -m map.dot tests/add.calc tests/mult.calc
$ dot map.dot -Tpng -omap.png
``` 
produces this output:
[Needs squashing]
=> First matcher module PR

src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/main.rs, tests/Test0.java, tests/Test1.java, tests/test_ast.rs, tests/test_hqueue.rs
This PR adds some more infrastructure needed by the GT matcher algorithm:
* A priority queue of height-ordered `NodeId`s has been added in the new `hqueue.rs` module.
* The user can set a number of thresholds from the command line.
* The API has been updated a little, to match the nomenclature in the GT paper.
* The `treediff::ast::Arena` type now takes one type variable, rather than two. The type of labels (i.e. the grammar production for each node) is now always `String`.
New CLI options:
```sh
Usage: rstreediff [options] <base-file> <diff-file>
rstreediff [options] <base-file> <diff-file> -d <file> ...
rstreediff (--help | --version)
Diff two input files.
Options:
-a, --ast         print AST of input files to STDOUT.
--debug LEVEL     debug level used by logger. Valid (case sensitive) …
```
=> Second matcher module PR

src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/main.rs, tests/Test1.java, tests/test_hqueue.rs
This is the third, but not the final PR for implementing a basic tree matcher. This PR introduces more scaffolding and basic algorithms which are necessary to implement the GT algorithm.
In this PR:
* In `hqueue.rs` various parts of the API have been changed to match the description in the GT paper
* A number of iterators have been added to the AST module, to traverse subtrees in a variety of orders (breadth-first, pre-order, post-order) which will all needed by algorithms coming in later PRs.
* In `matchers.rs` the mapping store has been re-written to use hash maps, which matched the GT implementation. This allows constant time look-ups of mappings.
* In `matchers.rs` a number of "similarity" measures have been implemented, which determine how similar two (previously matched) subtrees …
=> Third matcher module PR.

Cargo.lock, grammars/txt.l, grammars/txt.y, src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs, src/main.rs, tests/lorem1.txt, tests/lorem2.txt, tests/test_matcher.rs, tests/wiki1.txt, tests/wiki2.txt
This PR introduces some of the infrastructure needed to implement the end-to-end diffing tool, in particular the edit script generation algorithm. 
**NEEDS SQUASHING**
Specifically in this PR:
* A lot of churn on all the core APIs
* A simple matching algorithm based on Myers longest common subsequence algorithm (this matcher is the default for git-diff).
* An implementation of the edit script generation algorithm of Chawathe et al. (1996). When this algorithm terminates, it will have transformed the "base" AST into one that is isomorphic to the "diff" AST. It will also have transformed the partial mapping left by the matcher into a total mapping between the new base AST and the original diff AST. (T_1 and T_2 in the paper).
* Code to draw the result the final mapping left by the action …
=> First infrastructure PR

grammars/txt.y, src/lib/ast.rs, src/main.rs, tests/test_ast.rs, tests/test_hqueue.rs, tests/test_matcher.rs
The intention here is to enable the user to diff files for which we don't yet have a grammar.
=> If a grammar cannot be found, fall back to plain text parser.

src/lib/matchers.rs
This fixes a bug in the edit script generator which previously caused a crash (some debug code was lookup up nodes in the wrong ASTs). Also, it simplifies an iterator.
Could probably do with squashing.
=> Fix edit script generator

Cargo.lock, Cargo.toml, src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/lib/patch.rs, src/lib/sequence.rs, src/main.rs
This is the third PR to introduce significant new infrastructure, and it will be the last for a while.
This PR introduces coloured diffs on the terminal. At this point, even though the test cases in the repo are very small (in terms of file size) the size of the resulting parse trees is such that the graphviz output and debug output is often too large to look through in detail, this PR is intended to make debugging a little easier.
Because this feature is needed for debugging, the implementation has several deficiencies:
* Producing a diff is not especially efficient in either time or space.
* The output cannot be used to produce a patch.
* Some systems post-process diff output to make it either more accurate or more readable, this implementation does not. Inevitably the output will …
=> Third infrastructure PR

src/lib/action.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/matchers.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs
This PR:
* Removes the requirement for the type variable T to implement the `Display` trait
* Removes the implementation of `Display` for the types in `action.rs` -- these are not needed by the edit script generator
=> Simplify action by relaxing trait bounds.

Cargo.lock, Cargo.toml, src/lib/ast.rs, src/lib/mod.rs
This PR updates rstreediff to use the new `cfgrammar` API.
=> Update dependency APIs.

Cargo.lock, src/lib/action.rs, src/lib/ast.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/sequence.rs
Currently, line and column numbers are not used, so no behaviour has changed.
=> Add line and column numbers to AST nodes.

src/lib/ast.rs
=> yacc_to_statetable is now called from_yacc (and returns a tuple).

grammars/java.l, grammars/java.y, tests/Comment.java, tests/NestedComment.java, tests/test_ast.rs
Example test case:
```java
/* Multiline 1 */
public /* Multiline 2 */ class /* Multiline 3 */ Comment /* Multiline 4 */ {
// Single line comment.
} /* Multiline 5
*
*
*
*/
```
Parser output:
=> Add comments to Java grammar.

tests/test_ast.rs
This PR strips `\r` from pretty printed ASTs in the test suite, since expected results always assume UNIX line endings. This should enable the tests to work correctly in a Windows environment, for now. 
NB: This does not mean that Diffract will always support Windows users, for now cross-platform support is not a priority!
Fixes #37
=> Strip \r from pretty printed ASTs. 

src/lib/edit_script.rs, src/lib/matchers.rs
This fixes a bug that was introduced in #52
=> Test whether nodes were mapped by matcher (rather than the edit script generator).

src/lib/action.rs, src/lib/ast.rs, src/lib/edit_script.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/sequence.rs, src/main.rs, tests/test_ast.rs
Indentation has been stored inside AST nodes since the AST module was first written.
However, now we have whitespace-aware grammars, there is no need to store indentation separately.
The `Debug` trait (on `Node` and `Arena` types) now adds indentation to its output (similarly to `lrpar`).
Tests have been updated to match the new API.
In this PR, the `ast.rs` file has changed some functionality (the other files have just changed to match the new APIs). The diffs are unfortunately very large because a large number of test cases that needed changing, but the changes in functionality are relatively small.
This fixes a more fundamental problem about moving nodes. If we have this tree:
```
Expr +
INT 1
INT 2
```
and move the nodes around to make `INT 1` the new root, keeping indentation within …
=> Remove indent from AST nodes.

src/lib/action.rs, src/lib/ast.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs, src/main.rs, tests/test_ast.rs, tests/test_hqueue.rs
Fixes #57 
This PR:
* Introduces separate `FromNodeId` and `ToNodeId` types for `NodeId`, to differentiate *from* and *to* ASTs in the source code. This is intended to avoid bugs where actions are applied to the "wrong" tree.
* Implements the `From` trait for `NodeId`, `Node` and `Arena` in the `ast` module (only available when testing).
* Updates Diffract with respect to the lrpar API.
* Runs `rustfmt` over all affected modules.
It is probably worth reviewing by commit, since the `NodeId` commit is so large.
**NEEDS SQUASHING**
=> Fix issue 57

src/lib/action.rs, src/lib/ast.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs, tests/test_ast.rs
**NEEDS SQUASHING**
Fixes #49 
This PR introduces a small API change to rename the `value` of a node as `type` (node `label`s stay the same). 
This has been the cause of much confusion in the code base, and you will notice that there are places where very similar functions have swapped the order types and labels, or where one has been used where the other was expected, and so on.
To avoid further confusion, the unit tests (but not necessarily integration tests) now prefer `&str` to `String` for the type of node types. This avoids confusing between node types and labels and allows the type checker to report any future mistakes.
I've also removed the `hello_java` test from `tests/test_ast.rs` because its expected output was too long to sensibly maintain, and the test did not add anything to …
=> Use standard terms for type and labels of AST nodes.

rustfmt.toml
`chain_indent` no longer exists in the rustfmt TOML configuration, and using it with the latest rustfmt gives an error message. This PR brings the Diffract repo up to date with nightly.
See: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md for configuration details.
=> Update rustfmt config.

rustfmt.toml, src/lib/action.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/matchers.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs, tests/test_edit_script.rs, tests/test_matcher.rs
This PR adds interior mutability to mapping stores, so that we can pass them to functions without marking them mutable. I would suggest reviewing each commit separately (note there is a separate formatting commit).
**Needs squashing**
=> Add store ref cells

src/lib/action.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/gt_matcher.rs, src/lib/matchers.rs, src/lib/myers_matcher.rs, src/lib/sequence.rs, tests/test_edit_script.rs
The feature branch `new-edit-script-tests` adds some more tests (mostly integration tests so far) for the edit script generator and contains a (so far partial) fix for the bug in the generator. The code we recently merged into `master`, which wraps a `RefCell` around some elements of the `MappingStore` struct, is especially difficult to merge into the feature branch, and last time I tried I had to give up and abort the merge.
Part of the difficulty is that half-way through the merge we need to add an extra `RefCell` into the `MappingStore` struct (or alternatively mark a number of stores as mutable). Rather than do that in the merge, this PR isolates that change so that we can merge it into master now.
=> Wrap a RefCell around to_arena in MappingStore.

src/lib/ast.rs, src/main.rs
Two quick improvements to AST arenas:
1. Add the ability to delete and replace root nodes (needed for the work on the edit script)
2. Improve tests for the `children()` iterator.
Some rustfmt changes.
=> `ast` module improvements

src/lib/emitters.rs
This is useful for debugging, as several `debug!()` statements print out `NodeId` information.
[map_master.pdf](https://github.com/softdevteam/diffract/files/1762423/map_master.pdf)
[map_feature.pdf](https://github.com/softdevteam/diffract/files/1762426/map_feature.pdf)
=> Add `NodeId`s to GraphViz output.

tests/test_ast.rs
This bug was not caught previously, because the intended file not found failure (i.e. the missing lexer file) was triggered before the missing input file caused a panic.
=> Fix typo in test dealing with non-existent lexer file

src/lib/action.rs
This PR:
* Adds a new `size()` method, 
* Implements the `Debug` trait, and
* Implements the `PartialEq` 
for `EditScript` objects. The last of these is complicated, because we store edit scripts as a vector of boxed traits. These need to be downcast before calling `eq()` and we need to avoid unbounded recursion in the `eq()` method.
See also [this SO question](https://stackoverflow.com/questions/48952627/implementing-partialeq-on-a-boxed-trait).
=> Action module improvements

src/lib/ast.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/hqueue.rs, src/lib/matchers.rs, tests/CommentMinimal.java, tests/HelloMinimal.java, tests/common.rs, tests/test_edit_script.rs, tests/test_hqueue.rs
This PR contains a number of fixes for the edit script generator. It is probably easier to review commit-by-commit, and the commit messages contain details of each fix.
The only commit that needs some extra information is 5bfe448a1f18d3f41a7a2dda0ea1e569bf0bebc0 which "fixes" something that looked like a bug, but was actually something that makes no difference to the algorithms, but produced very confusing debug output. Here is an example from master branch: 
[master_edit.pdf](https://github.com/softdevteam/diffract/files/1794497/master_edit.pdf)
In this example, we have diff'd two files of different file types, meaning that in the original ASTs the two trees will have had different roots (with different types and labels). The Chawathe et al. 96 algorithm assumes that trees have the same …
=> Edit script fixes

.travis.yml, src/lib/ast.rs
Should be equivalent to the following GT code (but does not decorate the AST with sizes):
```rust
for (ITree t: tree.postOrder()) {
int size = 1;
if (!t.isLeaf())
for (ITree c: t.getChildren())
size += c.getSize();
t.setSize(size);
}
```
=> Calculate size of subtree.

Cargo.toml, src/lib/action.rs, src/lib/ast.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/fingerprint.rs, src/lib/gt_matcher.rs, src/lib/matchers.rs, src/lib/mod.rs, src/lib/myers_matcher.rs, src/lib/null_matcher.rs, src/lib/sequence.rs, src/main.rs, tests/common.rs
The fingerprinting module implements the algorithm described in M. Chilowicz, E. Duris, G. Roussel (2009) Syntax Tree Fingerprinting: A Foundation For Source Code Similarity Detection. This is used by the GumTree matcher algorithm.
The implementation here is based closely on the GumTree implementation. 
Implement [to_short_string()](https://github.com/GumTreeDiff/gumtree/blob/066d138201acb3c457bafb131a5a33fd820d1919/core/src/main/java/com/github/gumtreediff/tree/AbstractTree.java#L245) and [to_static_hash_string()](https://github.com/GumTreeDiff/gumtree/blob/066d138201acb3c457bafb131a5a33fd820d1919/core/src/main/java/com/github/gumtreediff/tree/AbstractTree.java#L228) on `NodeId`. Compute [tree isomorphism based on hashes](https://github.com/GumTreeDiff/gumtree/blob/066d138201acb3c457bafb1 …
=> Decorate ASTs with hashes of each node (needed by GumTree).

grammars/java-no-ws.l, grammars/java-no-ws.y, grammars/java.l, grammars/java.y, tests/test_ast.rs
This updates the Java grammar by copying over the lex and yacc files. Issue #90 suggests we go a bit further, and may be the subject of a future PR.
=> Update Java grammar to Java7.

Cargo.toml, src/lib/mod.rs, src/lib/qgram.rs, src/lib/zs_matcher.rs
Calculate a q-gram distance between strings. Needed by the Zhang-Shasha matcher.
Implementation based on the simmetrics library: https://github.com/Simmetrics/simmetrics
=> q-gram distance

src/lib/ast.rs, src/lib/chawathe98_matcher.rs, src/lib/fingerprint.rs, src/main.rs
Various improvements suggested by the compiler and clippy. Unfortunately there is a lot of this, and a `rustfmt` commit in the middle, so it won't be the easiest to review.
The first few commits are from various parts of the code base, followed by a number from the Chawathe 98 matcher code. I have ignored clippy suggestions on cyclomatic complexity and functions with too many arguments (some of the suggestions might be sensible, but they require more major surgery).
Needs much squashing.
=> Code cleanup

Cargo.toml, rustfmt.toml, src/lib/action.rs, src/lib/ast.rs, src/lib/chawathe98_matcher.rs, src/lib/emitters.rs, src/lib/fingerprint.rs, src/lib/gt_matcher.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/lib/parser.rs, src/lib/patch.rs, src/lib/qgram.rs, src/lib/similarity.rs, src/main.rs, tests/test_edit_script.rs
This PR:
* Factors out common ASTs used in many unit tests across the code base.
* Provides an API for loading ASTs from XML in test config. 
* Converts the common parse trees to XML.
The reason for doing this, other than avoiding code duplication, is to cut down on the amount of code in the unit tests, which is currently large and broadly unreadable. Also, this will make it easier in other PRs to load XML test data similar to that in the GT code base.
=> Refactor unit tests

src/lib/action.rs, src/lib/ast.rs, src/lib/mod.rs, tests/common.rs, tests/test_ast.rs
This is intended to help with debugging.
As an example, this AST:
```
^~"
"~"
"Expr"
"Term"
"Factor"
"INT" 1
```
becomes:
```
000: "^~"
001:   "~"
002:   "Expr"
003:     "Term"
004:       "Factor"
005:         "INT" 1
```
=> Prefix lines of pretty-printed ASTs with NodeIds.

src/lib/labelmaps.rs, src/lib/mod.rs
This module is similar to ones found in GT and Approxlib. It allows AST labels to be stored efficiently, as integers in a hash map.
This is needed by the RTED code.
=> Label maps

.travis.yml
This reverts commit d078a2818b2a77c93adc26461c62121009b8086a which fixed Travis to an old version of the nightly build.
=> Revert "Fix rust-nightly version in Travis."

src/lib/mod.rs
When I run clippy, I get several screens of output that I'm not interested in, which makes it more likely that I'll miss something important. This PR suppresses some warnings that we do not care about.
Specifically:
* Missing Default() traits.
* High cyclomatic complexity and too many function arguments.
* High type complexity.
=> Cleaner clippy output.

src/lib/action.rs, src/lib/ast.rs, src/lib/chawathe98_matcher.rs, src/lib/edit_script.rs, src/lib/emitters.rs, src/lib/fingerprint.rs, src/lib/gt_matcher.rs, src/lib/hqueue.rs, src/lib/matchers.rs, src/lib/mod.rs, src/lib/myers_matcher.rs, src/lib/null_matcher.rs, src/lib/patch.rs, src/lib/rted.rs, src/lib/sequence.rs, src/lib/similarity.rs, src/lib/zs_matcher.rs, src/main.rs, tests/common.rs, tests/test_ast.rs, tests/test_edit_script.rs, tests/test_hqueue.rs
This is a large but mechanical PR which improves the consistency of names within the code base. 
Differs take two input files or ASTs. Prior to this change, the code base referred to these either as `diff` and `base`, or `from` and `to`, or `src`, and `dst`. This PR  standardises names of variables, functions, methods and structs to consistently use `src` and `dst`.
=> Improve code consistency.

Cargo.toml, src/lib/parser.rs
This PR first ports Diffract to use the grmtools repositories and then factors out the token ID type (and another type that grmtools now requires) into `type` declarations, so that one only needs to chang things in one place.
=> Port to grmtools

src/lib/matchers.rs, src/lib/mod.rs, src/lib/multi_mappings.rs
This module contains a structure similar to a `matchers::MappingStore`. However, a mapping store holds unique mappings between the src and dst trees in the diff. Multi-mapping stores hold non-unique mappings (i.e. candidate mappings). This structure is used by GT and based on the GT Java code.
=> Implement multi-mapping store.

Cargo.toml, src/lib/action.rs, src/lib/ast.rs, src/lib/emitters.rs, src/lib/mod.rs, src/lib/parser.rs, src/main.rs, tests/test_ast.rs
This commit implements the standard library `Error` trait for all public errors in the crate (`ArenaError`, `EmitterError`, `ParseError`). The `quick_error` macro (from the quick-error crate) is used to simplify error definitions. This makes error handling more idiomatic.
In addition, we now need much less custom error handling in `main.rs`, as each error "holds" its own description and error message. This also makes the code a little easier to read, as error definitions and descriptions appear together in the relevant files.
To make this happen, some errors now hold extra information (such as file names and AST node ids. Errors in `ArenaError` which relate to nodes having unexpectedly few or many children now hold the id of the erroneous node, rather than the number of children that node …
=> Implement the Error trait.
